@baseUrl = http://localhost:3333

### 

# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "SUV",
    "description": "Categoria de carro SUV"
}

###

# @name list_categories
GET {{baseUrl}}/categories
Content-Type: application/json

###

# @name create_specification

POST {{baseUrl}}/specifications
Content-Type: application/json

{
    "name": "Câmbio automático",
    "description": "Carro com câmbio automático"
}

###

# @name create_user

POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Yan Carlos Oliveira",
    "email": "yan@gmail.com",
    "password": "1234",
    "driver_license": "123456"
}

###

# @name create_session

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "yan@gmail.com",
    "password": "1234"
}
