@baseUrl = http://localhost:3333

### 

# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "SUV",
    "description": "Categoria de carro SUV"
}

###

# @name list_categories
GET {{baseUrl}}/categories
Content-Type: application/json