version: "3.7"

services:
  database:
    image: postgres
    container_name: rent-car-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rent-car
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d rent-car"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    container_name: rent-car-api
    ports:
      - 3333:3333
    command: npm run dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      database:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
