version: "3.7"

services:
  app:
    build: .
    container_name: rent-car-api
    ports:
      - 3333:3333
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/app/src
        - action: sync
          path: ./tsconfig.json
          target: /usr/app/tsconfig.json
        - action: rebuild
          path: package.json
